### ISSUE TITLE
Border around each sector

### ISSUE THREAD

**Issue by SteMMo33** [isaacnguyen0809/Canvas-Donut-Chart#1]
Hello,
is it possible to draw the small border around each sector, and not only between sectors ??

Thanks!

**Comment by isaacnguyen0809** [comment]
@SteMMo33 Hi, I'm not really get you. Maybe, you want a border around the circle, right? If so, ofc

**Comment by SteMMo33** [comment]
Oh sorry, maybe an image is better :)
![Schermata 2024-03-01 alle 17 02 52](https://github.com/isaacnguyen0809/Canvas-Donut-Chart/assets/8493374/d11796b0-f977-4126-ab81-bfd4ef92a593)

**Comment by isaacnguyen0809** [comment]
okay, i got it. You can simply use canvas.drawCircle to draw a circle with PaintingStyle as stroke, like this `(final borderPaint = Paint()
    ..color = Colors.white
    ..strokeWidth = 2
    ..style = PaintingStyle.stroke;
    .....
    canvas.drawCircle(c, radius/2, borderPaint);
    )`
    
    
![Screenshot_1709311136](https://github.com/isaacnguyen0809/Canvas-Donut-Chart/assets/57831153/b4b50185-0327-4f95-9198-31a0034cffed)

**Comment by SteMMo33** [comment]
Yes .. very simple.
Sorry for silly question, thanks a lot !
